FROM python:3.10-slim-buster

WORKDIR /backend-flask

# Outside Container -> Inside Container
# This contains the libraries want to install to run the app
COPY requirements.txt requirements.txt

# Inside Container
# Install the python libraries used for the app

RUN pip3 install -r requirements.txt


COPY . .

ENV FLASK_ENV=development

EXPOSE ${PORT}
CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0", "--port=4567"]